# data-retrieval-deployment.yaml
# Deploy only once, so we use a Job instead of a Deployment
# Run only once, so we use restartPolicy: Never

apiVersion: batch/v1
kind: Job
metadata:
  name: data-retrieval-job
spec:
  template:
    metadata:
      labels:
        app: data-retrieval-pod
    spec:
      containers:
      - name: data-retrieval
        image: stormit237/data-retrieval  # Replace with your Docker image name
        imagePullPolicy: Always        # Force the pull of the container image - used for testing purposes
        env:
        - name: REDIS_HOST
          value: redis.default.svc.cluster.local  # The host of the Redis service
        - name: AWS_ACCESS_KEY_ID
          value: ""  # Fill in with the Secret key value
        - name: AWS_SECRET_ACCESS_KEY
          value: ""  # Fill in with the Secret key value
      restartPolicy: Never

# There is no service for this Job, because the job does not need to be accessed externally or expose any ports. 
# It will connect to the Redis service internally within the cluster. 
# The Redis service itself still needs a service definition to allow other pods to connect to it.

